// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znwmcurcqguekhemjmdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpud21jdXJjcWd1ZWtoZW1qbWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzE2MTIsImV4cCI6MjA3MzYwNzYxMn0.3PEiTE8DzdIXDsscQtaXTVc8GLk5vGrRnjDuBS5Dgnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});